// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";
import * as Vitest from "vitest";
import * as Core__Int from "@rescript/core/src/Core__Int.mjs";
import * as VitestBdd from "vitest-bdd";
import * as Core__Option from "@rescript/core/src/Core__Option.mjs";

VitestBdd.Given("I have a table", (function (param, data) {
        var step = param.step;
        var match = Tilia.signal([]);
        var setRecords = match[1];
        var records = match[0];
        var match$1 = Tilia.signal({
              name: "",
              age: ""
            });
        var setRecord = match$1[1];
        var record = match$1[0];
        step("I convert the table to records", (function () {
                setRecords(VitestBdd.toRecords(data));
              }));
        step("I select record {number}", (function (index) {
                setRecord(Core__Option.getExn(records.value[index], undefined));
              }));
        step("selected name should be {string}", (function (value) {
                Vitest.expect(record.value.name).toBe(value);
              }));
        step("selected age should be {number}", (function (value) {
                Vitest.expect(Core__Int.fromString(record.value.age, undefined)).toBe(value);
              }));
      }));

export {
  
}
/*  Not a pure module */
