// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";
import * as Core__Array from "@rescript/core/src/Core__Array.mjs";

function make(name) {
  var match = Tilia.signal(0);
  var setResult = match[1];
  var result = match[0];
  return Tilia.tilia({
              add: (function (a, b) {
                  setResult(a + b);
                }),
              sum: (function (numbers) {
                  setResult(Core__Array.reduce(numbers, 0, (function (acc, n) {
                              return acc + n;
                            })));
                }),
              subtract: (function (a, b) {
                  setResult(a - b);
                }),
              multiply: (function (a, b) {
                  setResult(a * b);
                }),
              divide: (function (a, b) {
                  setResult(a / b);
                }),
              result: Tilia.computed(function () {
                    return result.value;
                  }),
              title: name
            });
}

export {
  make ,
}
/* Tilia Not a pure module */
