// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Tilia from "tilia/src/Tilia.mjs";

function make(name) {
  var result = Tilia.signal(0);
  var title = Tilia.signal(name);
  return Tilia.tilia({
              add: (function (a, b) {
                  result.value = a + b;
                }),
              subtract: (function (a, b) {
                  result.value = a - b;
                }),
              multiply: (function (a, b) {
                  result.value = a * b;
                }),
              divide: (function (a, b) {
                  result.value = a / b;
                }),
              result: Tilia.computed(function () {
                    return result.value;
                  }),
              title: Tilia.computed(function () {
                    return title.value;
                  })
            });
}

export {
  make ,
}
/* Tilia Not a pure module */
